@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Inventory *-right-> "1" UniqueIngredientList
Inventory *-right-> "1" UniqueTagList
UniqueTagList -[hidden]down- UniqueIngredientList
UniqueTagList -[hidden]down- UniqueIngredientList

UniqueTagList -right-> "*" Tag
UniqueIngredientList -right-> Ingredient

Ingredient -up-> "*" Tag

Ingredient *--> Name
Ingredient *--> Phone
Ingredient *--> Email
Ingredient *--> Address
@enduml
