@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

package Storage as StoragePackage {

package "UserPrefs Storage" #F4F6F6{
Class "<<interface>>\nUserPrefsStorage" as UserPrefsStorage
Class JsonUserPrefsStorage
}

Class "<<interface>>\nStorage" as Storage
Class StorageManager

package "Inventory Storage" #F4F6F6{
Class "<<interface>>\nInventoryStorage" as InventoryStorage
Class JsonInventoryStorage
Class JsonSerializableInventory
Class JsonAdaptedIngredient
}

package "RecipeBook Storage" #F4F6F6{
Class "<<interface>>\nRecipeBookStorage" as RecipeBookStorage
Class JsonRecipeBookStorage
Class JsonSerializableRecipeBook
Class JsonAdaptedRecipe
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Storage

StorageManager .up.|> Storage
StorageManager -up-> "1" UserPrefsStorage
StorageManager -up-> "1" InventoryStorage
StorageManager -up-> "1" RecipeBookStorage

Storage -left-|> UserPrefsStorage
Storage -right-|> InventoryStorage
Storage -right|> RecipeBookStorage

JsonUserPrefsStorage .up.|> UserPrefsStorage
JsonInventoryStorage .up.|> InventoryStorage
JsonInventoryStorage ..> JsonSerializableInventory
JsonSerializableInventory --> "*" JsonAdaptedIngredient

JsonRecipeBookStorage .up.|> RecipeBookStorage
JsonRecipeBookStorage ..> JsonSerializableRecipeBook
JsonSerializableRecipeBook --> "*" JsonAdaptedRecipe
JsonAdaptedRecipe --> "*" JsonAdaptedIngredient

@enduml
